name: CI - Prerelease

on:
  push:
    branches:
      - release/*

# env varialble for GITHUB_TOKEN
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # get release branch semver from branch name (e.g. release/1.2.0)
      - name: Get release branch semver
        id: release_branch_semver
        run: |
          echo "::set-output name=semver::${GITHUB_REF#refs/heads/release/}"

      # create or bump semantic version based on release branch semver (e.g. 1.2.0-rc.0)
      - name: Create or bump semantic version
        id: semantic_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: prerelease
          default_preid: rc
          prerelease_branches: release/*
