# create a github action that creates a semver tag when pushed to a release branch
# ex. release/1.1.0 would create a tag 1.1.0-rc.0 and increment each time the branch is updated
# when pushed to master it would create a tag 1.1.0 and increment each time master is updated

# this is the name of the action
name: Semver Tag

# this is the event that triggers the action
on:
  push:
    branches:
      - release/*
      - master

# this is the list of jobs that will be run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | cut -d / -f 3)
          echo ::set-output name=version::$VERSION
      - name: Create Tag
        id: semver
        uses: mathieudutour/github-tag-action@v5
        with:
          # this uses the github ref to determine the version
          # ex. refs/heads/release/1.1.0 would result in v1.1.0-rc.0
          # ex. refs/heads/master would result in v1.1.0
          # tag: ${{ github.ref }}
          tag: v${{ steps.version.outputs.version }}
          # this uses the github ref to determine the version
          # ex. refs/heads/release/1.1.0 would result in 1.1.0-rc.0
          # ex. refs/heads/master would result in 1.1.0
          # release_branches: release/*
          release_branches: refs/heads/release/*
