name: CI - Prerelease

on:
  push:
    branches:
      - release/*

# env varialble for GITHUB_TOKEN
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine branch version
        id: determine-version
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          version=${branch_name#release/}
          echo "::set-output name=version::$version"
        shell: bash
      - name: Determine last tag
        id: determine-tag
        run: |
          last_tag=$(git describe --abbrev=0 --tags --match 'v*.*.*-*')
          echo "::set-output name=last_tag::$last_tag"
        shell: bash
      - name: Bump version
        id: bump-version
        uses: vishnubob/autoincrement-semver@v1
        with:
          bump_level: pre
          version: ${{ steps.determine-tag.outputs.last_tag }}
      - name: Create new tag
        run: |
          git tag ${{ steps.bump-version.outputs.new_version }}
          git push --tags
