# create a github action that creates a semver tag when pushed to a release branch
# ex. release/1.1.0 would create a tag 1.1.0-rc.0 and increment each time the branch is updated
# when pushed to master it would create a tag 1.1.0 and increment each time master is updated

# this is the name of the action
name: Semver Tag

# this is the event that triggers the action
on:
  push:
    branches:
      - release/*
      - master

# this is the list of jobs that will be run
jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine version
        id: determine-version
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          version=${branch_name#release/}
          echo "::set-output name=version::$version"
        shell: bash
      - name: Determine last tag
        id: determine-tag
        run: |
          last_tag=$(git describe --abbrev=0 --tags --match 'v*.*.*')
          echo "::set-output name=last_tag::$last_tag"
        shell: bash
      - name: Bump version
        id: bump-version
        run: |
          IFS='.' read -ra version_parts <<< "${{ steps.determine-tag.outputs.last_tag }}"
          patch=$(( ${version_parts[2]} + 1 ))
          new_tag="${version_parts[0]}.${version_parts[1]}.$patch"
          echo "::set-output name=new_tag::$new_tag"
        shell: bash

      # push the new tag to the repo and create a release
      - name: Push tag
        id: push-tag
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          custom_tag: ${{ steps.bump-version.outputs.new_tag }}
          tag_prefix: ""
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump-version.outputs.new_tag }}
          name: Release ${{ steps.bump-version.outputs.new_tag }}
          body: ${{ steps.push-tag.outputs.changelog }}
